version: "3.9"

services:
  rusbnb_app:
    container_name: rusbnb_app
    image: dockerhub-flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@rusbnb_db:5432/postgres
    depends_on:
      - rusbnb_db
  rusbnb_db:
    container_name: rusbnb_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}